import type { Metadata } from "next";
import { PT_Sans } from "next/font/google";
import "./../styles/globals.css";

const sans = PT_Sans({
  subsets: ["cyrillic"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn-uicons.flaticon.com/2.4.0/uicons-brands/css/uicons-brands.css"
        ></link>
      </head>
      <body suppressHydrationWarning={true} className={sans.className}>
        {children}
      </body>
    </html>
  );
}
